name: Basic CI Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COURSE: DevOps
      TRAINER: Prajwal

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Repository Name
        run: echo "Repository = ${{ github.repository }}"

      - name: Print Branch Name
        run: echo "Branch = ${{ github.ref_name }}"

      - name: Print Commit ID
        run: echo "Commit = ${{ github.sha }}"

      - name: Print Environment Variables
        run: |
          echo "Course = $COURSE"
          echo "Trainer = $TRAINER"

      - name: Multiple Commands
        run: |
          echo "Step 1"
          echo "Step 2"
          echo "Step 3"
