name: Secrets and Schedule

on:
  workflow_dispatch:

  schedule:
    - cron: "0 10 * * *"

jobs:
  secrets-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read DockerHub Username
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "::add-mask::$DOCKER_USERNAME"
          echo "Docker Username: $DOCKER_USERNAME"

      - name: Success Message
        run: echo "Workflow executed successfully!"
